---

packages:
  - sudo
  - rsync
  - vim
  - curl
  - zip
  - bzip2
  - apt-transport-https
  - htop
  - pydf
  - python3-setuptools
  - python3-dev
  - python3-pip
  - python3-venv
  - build-essential
  - python3-kubernetes

lb_addresses: &lb_addresses []

k3s:
  enabled: true
  kubeconfig:
    K8S_AUTH_KUBECONFIG: &config_path /etc/rancher/k3s/k3s.yaml
    KUBECONFIG: *config_path
  extras:
    traefik: false
    servicelb: true
    metallb: &metallb false
    san: true
  network:
    service: 10.0.20.0/24
    cluster: 10.0.21.0/24
    bgp: &bgp
      my_asn: &my_asn "65000"
      peer_asn: *my_asn
      peer: 10.0.1.30
    loadbalancer:
      ipAddressPools: *lb_addresses

addons:
  - name: metallb
    url: https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml
    enabled: *metallb
    bgp:
      enabled: false
      <<: *bgp
    lb_ip_address: "{{ k3s.network.loadbalancer.ipAddressPools }}"
  - name: nginx
    helm: false
    url: "https://helm.nginx.com/stable"
    component: ingress
